encoding: UTF-8
theme: jekyll-theme-minimal
url: "https://blog.rabbit-gather.com"
canonical_url: "https://blog.rabbit-gather.com"
enforce_ssl: blog.rabbit-gather.com
title: 兔給得資訊公司
tagline: 促進網頁社群和工程師的媒合
description: 促進網頁社群和工程師的媒合
locale: zh_TW
theme: jekyll-theme-minimal
logo: assets/logo.png
type: website
permalink: pretty
locale: zh_Hant_TW
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
seo: 
  type: Organization
page:
  date: 2022-07-01
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-image-size
